[build]
  publish = "/"
  command = ""

[[headers]]
  for = "/assets/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/assets/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/assets/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=300, stale-while-revalidate=86400"
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=300, stale-while-revalidate=86400"
